### ISSUE TITLE
Clarify handling of bad input

### ISSUE THREAD

**Issue by AbdallahS** [dmbaturin/ocaml-tsort#10]
Consider the following dependencies: 1 -> 2, 3 and 2 -> 1. A natural but inappropriate way to specify it is `[(1, [2]); (2, [1]); (1, [3])]`, in other words, a list where each pair expresses some possibly incomplete dependency. The current behaviour of `Tsort` on these is not consistent: sometimes it rejects the input with an `assert false` and sometimes it computes the meaningful output.

    utop # let l = [(1, [3]); (2, [1]); (1, [2])];;
    val l : (int * int list) list = [(1, [3]); (2, [1]); (1, [2])]
    ──────────────
    utop # Tsort.sort_strongly_connected_components l;;
    - : int list list = [[3]; [2; 1]]
    ──────────────
    utop # let l = [(1, [2]); (2, [1]); (1, [3])];;
    val l : (int * int list) list = [(1, [2]); (2, [1]); (1, [3])]
    ──────────────
    utop # Tsort.sort_strongly_connected_components l;;
    Exception: Assert_failure ("src/lib/tsort.ml", 287, 22).

It would be nice to
* Have a consistent behaviour: always reject (with a readable error message), or always accept these inputs
* State how such inputs are treated in the documentation.

**Comment by dmbaturin** [comment]
This is an inconsistency indeed! Thanks for pointing it out, I'll look into it.

**Comment by dmbaturin** [comment]
I think I've finally found the issue. [This commit](https://github.com/dmbaturin/ocaml-tsort/commit/066835d2927ead874ead5fb2562d04b2f8a06431) should fix it, please test.

```
utop # Tsort.sort_strongly_connected_components [(1, [3]); (2, [1]); (1, [2])] ;;
- : int list list = [[3]; [2; 1]]

utop # Tsort.sort_strongly_connected_components [(1, [2]); (2, [1]); (1, [3])] ;;
- : int list list = [[3]; [2; 1]]

```

If it works correctly for you, I'll make a new OPAM release.

**Comment by AbdallahS** [comment]
It seems to be working on my end. This isn't any extensive testing, though: I simplified my code by avoiding manually regrouping dependencies (which I had to do to work around the bug in the default version of tsort) and in the default version of tsort my code crashes on some instances (with the assert false previously mentioned) but it doesn't crash with the current commit.

Thanks for the fix!

**Comment by dmbaturin** [comment]
Thanks for testing! I want to do some minor clean-up, and maybe also add more descriptive messages for the other instances of `assert false`. @mjambon left quite a few of them and I can't tell offhand what condition could cause the remaining ones. :)

**Comment by AbdallahS** [comment]
Sounds like a good plan. No rush. I'll use my local clone of tsort for now and once you release a new version on opam, I'll go back to the package-managed version.

Thanks for tsort!

**Comment by dmbaturin** [comment]
Out of curiosity: what's your project and how tsort is used there?

**Comment by AbdallahS** [comment]
I'm working on a grounding language for propositional logic (to make using SAT solvers easier). The grounding process requires applying production rules to generate all variables and clauses. If the production rules are recursive, then we need to apply them repeatedly until a fixpoint is reached. Identifying SCCs and a topological sort makes it possible to compute the fixpoint faster by progressing through the productions rules in the order prescribed by the topological sort and only looping within SCCs.

There are probably faster ways to do it (one could start by looking at the DATALOG literature for a start), but the approach I'm using is a sweet spot in the tradeoff between complexity of implementation and performance.

The project is at https://github.com/vale1410/bule (I'm doing a rewrite in OCaml in folder `bule2` to improve performance and extend the expressivity. Recursive production rules is one of the extensions.)

I might use tsort in two other projects, but the use case is similar: identify SCCs and a topological sort to help compute a fixpoint of production rules. One of the project has a local implentation of Tarjan's algorithm (based off wikipedia pseudo-code) but I may replace it with a call to tsort when I get around to doing it (and after I've clarified for myself the pros and cons). The other project doesn't support recursive rules yet, but it will at some point and tsort will help me get there easier.
